### ISSUE TITLE
Windows build is not working

### ISSUE THREAD

**Issue by sdc50** [conda-forge/whitebox_tools-feedstock#3]
Windows packages are not being built. @dharhas do you know if is this a problem with the recipe or is there an issue with Whitebox being compiled on Windows?

**Comment by sdc50** [comment]
Is it possible to see the AppVeyor builds for this project? I guess I don't understand the conda-forge build systems well enough to know where to look.

**Comment by sdc50** [comment]
Okay, it looks like the files are being built for [Windows](https://anaconda.org/conda-forge/whitebox_tools/files), but they are [not installable](https://ci.appveyor.com/project/dharhas/quest/build/1.0.280/job/pe3i3xojgnyv55nk) for some reason.

**Comment by dharhas** [comment]
Have you tried installing just the whitebox_tools in a new environment. We are currently packaging whitebox_tools for py35 and py36 for win64, maybe a quest dependency is forcing the dependency solver to look for a different version.

**Comment by dharhas** [comment]
Maybe AppVeyor only uses Win32, extracted from AppVeyor log:

```
           channel URLs : https://repo.anaconda.com/pkgs/main/win-32
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-32
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-32
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-32
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-32
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Miniconda3\pkgs
                          C:\Users\appveyor\AppData\Local\conda\conda\pkgs

```

I don't see a win64 in there. If we need a win32 version we will have to compile whitebox_tools from scratch. Upstream only builds the win64 binary.

**Comment by dharhas** [comment]
@sdc50 I think there is a way to force appveyor to use win64 but I quick google didn't turn up enough information

**Comment by sdc50** [comment]
@dharhas yes, I think the win64 is the key. I was able to verify that whitebox_tools is installable on Windows, but it was 64-bit. I'll take a look into configuring appveyor appropriately.

**Comment by sdc50** [comment]
Configuring AppVeyor to use 64-bit environments [is working](https://ci.appveyor.com/project/dharhas/quest/build/1.0.287).
